### creating one dimensional numpy array(Vector)

In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4,5]) 

array([1, 2, 3, 4, 5])

In [5]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
type(a)

numpy.ndarray

### creating two dimensional numpy array (Matrix)

In [10]:
b=np.array([1,2,3],[4,5,6])
b

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [11]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b=np.array([[1,2,3],[4,5,6,7,8]])
b

C:\Users\Premalatha\AppData\Local\Temp\ipykernel_7908\2510602567.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[1,2,3],[4,5,6,7,8]])


array([list([1, 2, 3]), list([4, 5, 6, 7, 8])], dtype=object)

In [15]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [17]:
np.array([1,0,3],dtype=bool)

array([ True, False,  True])

In [18]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10,3)

array([1, 4, 7])

In [21]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
np.arange(10).reshape(5,3)

ValueError: cannot reshape array of size 10 into shape (5,3)

In [23]:
np.ones(3,4)

TypeError: Cannot interpret '4' as a data type

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
np.random.rand(3,5)

array([[0.29795546, 0.64774399, 0.18513341, 0.82916992, 0.0199776 ],
       [0.98825885, 0.01578619, 0.64305135, 0.13976979, 0.60109792],
       [0.60184238, 0.36279407, 0.68502943, 0.941572  , 0.88390343]])

In [29]:
np.random.randn(3,5)

array([[-1.95508557, -0.88879556, -1.06895502, -0.09034619, -0.97027166],
       [ 1.37074559,  1.01841666, -0.73852026, -0.07814917, -0.98258394],
       [ 1.10471272,  1.23702759,  0.12229838, -0.81246609,  1.950544  ]])

In [31]:
np.random.randint(3,50)

7

In [34]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [35]:
np.linspace(-2,2,5)

array([-2., -1.,  0.,  1.,  2.])

In [36]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.identity(3,int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
a1=np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a2=np.arange(10,dtype=float)
a2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
a2=a2.reshape(2,5)
a2

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [66]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
a4=np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
a1.ndim

1

In [51]:
a2.ndim

2

In [53]:
a3.ndim

3

In [54]:
a4.ndim

3

In [55]:
a1.shape

(10,)

In [56]:
a2.shape

(2, 5)

In [68]:
a3.shape

(2, 2, 2)

In [58]:
a4.shape

(3, 3, 3)

In [59]:
a1.size

10

In [60]:
a2.size

10

In [62]:
a3.size

27

In [64]:
a4.size

27

In [67]:
a3.size

8

### Changing data type

In [72]:
x=np.array([1.9,2.0,3.0])
x

array([1.9, 2. , 3. ])

In [73]:
x.astype(int)

array([1, 2, 3])

In [74]:
a=np.arange(12).reshape(3,4)

In [75]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
a+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [77]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [78]:
a-5

array([[-5, -4, -3, -2],
       [-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

In [79]:
a/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [80]:
a**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [81]:
a//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [82]:
a%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [88]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
b>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [90]:
b>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [91]:
a+b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [92]:
a*b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [93]:
a-b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [94]:
a/b

C:\Users\Premalatha\AppData\Local\Temp\ipykernel_7908\1348051284.py:1: RuntimeWarning: invalid value encountered in divide
  a/b


array([[nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [95]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
c=np.random.random((3,3))
c

array([[0.27830116, 0.93231112, 0.20408843],
       [0.2994931 , 0.7870418 , 0.24115418],
       [0.79471513, 0.6198321 , 0.2181249 ]])

In [101]:
a=np.round(c*100)
a

array([[28., 93., 20.],
       [30., 79., 24.],
       [79., 62., 22.]])

In [102]:
np.max(a)

93.0

In [103]:
np.min(a)

20.0

In [104]:
np.sum(a)

437.0

In [105]:
np.prod(a)

319206719462400.0

In [106]:
np.max(a,axis=1)

array([93., 79., 79.])

In [107]:
np.min(a,axis=1)

array([20., 24., 22.])

In [109]:
np.max(a,axis=0)

array([79., 93., 24.])

In [110]:
np.prod(a,axis=0)

array([ 66360., 455514.,  10560.])

In [111]:
np.mean(a)

48.55555555555556

In [112]:
np.mean(a,axis=1)

array([47.        , 44.33333333, 54.33333333])

In [113]:
np.mean(a,axis=0)

array([45.66666667, 78.        , 22.        ])

In [114]:
np.median(a,axis=1)

array([28., 30., 62.])

In [115]:
np.median(a,axis=0)

array([30., 79., 22.])

In [116]:
np.std(a,axis=1)

array([32.69046752, 24.63511496, 23.89328125])

In [118]:
np.var(a,axis=1)

array([1068.66666667,  606.88888889,  570.88888889])

In [119]:
np.sin(a)

array([[ 0.27090579, -0.94828214,  0.91294525],
       [-0.98803162, -0.44411267, -0.90557836],
       [-0.44411267, -0.7391807 , -0.00885131]])

In [120]:
np.cos(a)

array([[-0.96260587,  0.3174287 ,  0.40808206],
       [ 0.15425145, -0.89597095,  0.42417901],
       [-0.89597095,  0.67350716, -0.99996083]])

In [121]:
np.tan(a)

array([[-0.2814296 , -2.98738626,  2.23716094],
       [-6.4053312 ,  0.49567753, -2.1348967 ],
       [ 0.49567753, -1.09750978,  0.00885166]])